#!/bin/bash

# extracts the current directory when running getPath
#
# example: 
# [/open/DEV/hack1.0/ $ ] FW/getPath # output is hack1.0
  

pwd | sed 's/\// /g' > abcdefgh
w=`wc -w abcdefgh | cut -d' ' -f1`
w=`expr $w + 1`
cat abcdefgh | cut -d' ' -f$w
rm abcdefgh
