#!/bin/bash

abort()
{
	if [ $# -gt 1 ]
	then
		echo failed to process $$ $0 because $1
	else
		echo failed to process $$ $0
	fi
	echo process $$ exiting
	exit 1
}

if [ ! -e /home/open/logs ]
then
	mkdir /home/open/logs
else
	echo >> /home/open/logs/tarball_build.log
	echo >> /home/open/logs/tarball_build.log
	echo >> /home/open/logs/tarball_build.log
	echo ****************************************************** >> /home/open/logs/tarball_build.log
	echo >> /home/open/logs/tarball_build.log
	echo >> /home/open/logs/tarball_build.log
	echo >> /home/open/logs/tarball_build.log
fi

echo `date` >> /home/open/logs/tarball_build.log
echo Welcome to `hostname`! >> /home/open/logs/tarball_build.log

echo -n "Which group do you want to build? [DEV, ALPHA, PRODUCTION]: "
read GROUP

if [ $GROUP = "DEV" ] || [ $GROUP = "ALPHA" ] || [ $GROUP = "PRODUCTION" ]
then
	echo -n "Which hack version do you want to build? [1.0, 2.0, 2.2a]: "
	read hackVER

	if [ $hackVER = "1.0" ] || [ $hackVER = "2.0" ] || [ $hackVER = "2.2a" ]
	then
		echo -n "Enter the Major [ex: 5]: "
		read MAJOR
		echo -n "Enter the Minor [ex: 12]: "
		read MINOR
		echo -n "Enter the TAG if needed [ex: RC3, RC1+, RC2+ (2.2a), hack, hack+, hack+ (2.2a)]: "
		read TAG
		echo -n "Enter the kernel version [ex: 013]: "
		read KERNEL
		echo -n "Enter the name of the SVN leaf dir [ex: tags, trunk, trunk_5.12, etc]: "
		read LEAF
		echo -n "Enter the name of the RESPOSITORY checkout [ex: 5.12-RC2]: "
		read REPOSITORY
		echo changing to /open/$GROUP >> /home/open/logs/tarball_build.log
		cd /open/$GROUP

		echo removing /open/$GROUP/hack${hackVER} for clean update >> /home/open/logs/tarball_build.log
		sudo rm -rf /open/$GROUP/hack${hackVER}

		echo -n "Enter the revision number or just HEAD [ex: 5045]: "
		read REVISION
		echo "updating with most current source code from /svn/hack/$LEAF/$REPOSITORY to $hackVER" >> /home/open/logs/tarball_build.log
		svn co -r$REVISION svn://svn.office.open.net/hack/$LEAF/$REPOSITORY hack${hackVER}
		echo cd /open/$GROUP/hack${hackVER} >> /home/open/logs/tarball_build.log
		cd hack${hackVER}

		SVNREV=`svnversion -c | cut -d : -f2 | cut -d M -f1 | cut -d S -f1`

		if [ $hackVER = "1.0" ]
		then
			VMEM=128
		else
			VMEM=256
		fi

		echo "$MAJOR" > open/hack/src/appVersion.dat
		echo "$MINOR">> open/hack/src/appVersion.dat
		echo "$TAG" >> open/hack/src/appVersion.dat
		echo "$SVNREV" >> open/hack/src/appVersion.dat

		case $hackVER in
			"1.0") make config_hack_1_0 ;;
			"2.0") make config_hack_2_0 ;;
			"2.2a") make config_hack_2_2 ;;
		esac
		echo | make
		echo y | make install
		cd /open/$GROUP/hack${hackVER}/FW
		echo Entering FW stage
		echo
		echo
		./collect $KERNEL $VMEM $hackVER
	else
		abort "no such version $hackVER"
	fi
else
	abort "no such group $GROUP"
fi
