#!/bin/bash

echo moving files to another dir

echo
echo
echo "Type the files you want moved, followed by [ENTER]:"

read files

echo "Type the directory that you want to move files to, followed by [ENTER]:"

read directory

if [ ! -d "$directory" ]
then
	echo Directory $directory does not exist.
  echo
  echo Would you like to create $directory [y/n]?

  read answer

  if [ $answer == 'y' ]
  then
    mkdir $directory
  else
    echo
    echo Aborting.
    echo
    exit
  fi
fi

for x in $files
do
  if [ ! -d "$x" ]
  then
      echo "moving $x to $directory"
    mv $x $directory

  fi
done
